plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.vietride'
version = '1.0.0'

android {
  namespace "com.vietride.vnpay"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
    consumerProguardFiles "consumer-rules.pro"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  maven { url uri("${projectDir}/repo") }
}

dependencies {
  implementation "com.android.support:support-v4:28.0.0"
  implementation "com.vnpay:merchant:1.0.25"
  implementation "com.google.code.gson:gson:2.8.9"
  implementation "com.squareup.okhttp3:okhttp:4.9.2"
}
