import type { ViewStyle } from 'react-native';
import { colors } from './colors';
import { borderRadius, shadows } from './spacing';
import type { AppTheme, ThemeColors, ThemeComponentTokens, ThemeEffectTokens, ThemeVariant } from './types';

const continuous = { borderCurve: 'continuous' } as ViewStyle;

const shadow = (
  boxShadow: string,
  legacy: ViewStyle,
): ViewStyle =>
  ({
    ...legacy,
    boxShadow,
  }) as ViewStyle;

const classicColors: ThemeColors = {
  ...colors,
  primary: '#006A67',
  primaryLight: '#2AC1BC',
  primaryDark: '#004A48',
  primaryFaded: '#EAF8F7',
  accentLight: '#71F7F1',
  accentDark: '#00504d',
  background: '#F7F9FF',
  surface: '#FFFFFF',
  surfaceAlt: '#F1F4F9',
  surfaceElevated: '#FFFFFF',
  textPrimary: '#181C20',
  textSecondary: '#3C4948',
  textTertiary: '#6C7A78',
  border: '#BBC9C8',
  borderFocused: '#006A67',
  divider: '#E5E8EE',
  overlay: 'rgba(24, 28, 32, 0.54)',
  overlayLight: 'rgba(24, 28, 32, 0.25)',
  skeleton: '#EBEBF3',
  skeletonHighlight: '#E0E3E8',
};

const liquidLightColors: ThemeColors = {
  ...colors,
  primary: '#007D78',
  primaryLight: '#33D3CD',
  primaryDark: '#005B57',
  primaryFaded: 'rgba(0, 154, 148, 0.12)',
  accent: '#2AC1BC',
  accentLight: '#80FFF8',
  accentDark: '#006A67',
  background: '#EFF7F8',
  surface: 'rgba(255, 255, 255, 0.62)',
  surfaceAlt: 'rgba(255, 255, 255, 0.38)',
  surfaceElevated: 'rgba(255, 255, 255, 0.76)',
  textPrimary: '#13211F',
  textSecondary: '#435A57',
  textTertiary: '#70817F',
  border: 'rgba(0, 91, 87, 0.16)',
  borderFocused: '#007D78',
  divider: 'rgba(0, 91, 87, 0.10)',
  overlay: 'rgba(19, 33, 31, 0.38)',
  overlayLight: 'rgba(19, 33, 31, 0.16)',
  skeleton: 'rgba(255, 255, 255, 0.56)',
  skeletonHighlight: 'rgba(255, 255, 255, 0.84)',
};

const liquidDarkColors: ThemeColors = {
  ...colors,
  primary: '#55F1E8',
  primaryLight: '#9FFFF8',
  primaryDark: '#BFFFFB',
  primaryFaded: 'rgba(85, 241, 232, 0.13)',
  accent: '#55F1E8',
  accentLight: '#BFFFFB',
  accentDark: '#21BDB5',
  background: '#061313',
  surface: 'rgba(17, 31, 31, 0.66)',
  surfaceAlt: 'rgba(255, 255, 255, 0.07)',
  surfaceElevated: 'rgba(20, 38, 38, 0.82)',
  textPrimary: '#F4FFFD',
  textSecondary: '#BFD7D3',
  textTertiary: 'rgba(191, 215, 211, 0.66)',
  textInverse: '#031312',
  textDisabled: 'rgba(191, 215, 211, 0.38)',
  successLight: 'rgba(85, 241, 232, 0.15)',
  warningLight: 'rgba(255, 224, 118, 0.18)',
  errorLight: 'rgba(255, 116, 116, 0.16)',
  infoLight: 'rgba(85, 241, 232, 0.12)',
  divider: 'rgba(255, 255, 255, 0.09)',
  border: 'rgba(174, 255, 249, 0.14)',
  borderFocused: '#9FFFF8',
  overlay: 'rgba(3, 10, 10, 0.72)',
  overlayLight: 'rgba(3, 10, 10, 0.48)',
  skeleton: 'rgba(255, 255, 255, 0.08)',
  skeletonHighlight: 'rgba(255, 255, 255, 0.16)',
};

const classicEffects: ThemeEffectTokens = {
  isLiquid: false,
  ambientGlow: 'rgba(42, 193, 188, 0.10)',
  glassOverlay: 'rgba(24, 28, 32, 0.54)',
  glassStroke: colors.divider,
  glassHighlight: colors.surface,
  glassSurface: colors.surface,
  glassSurfaceSoft: colors.surfaceAlt,
  glassSurfaceStrong: colors.surfaceElevated,
  glassBorder: colors.divider,
  glassBorderStrong: colors.border,
  glassSheen: colors.transparent,
  glassTint: colors.transparent,
  fieldSurface: colors.surfaceAlt,
  fieldBorder: colors.divider,
  tabBarSurface: colors.surface,
  tabActiveSurface: colors.primaryFaded,
  scrim: colors.overlay,
  cardShadow: shadows.sm,
  floatingShadow: shadows.lg,
};

const liquidLightEffects: ThemeEffectTokens = {
  isLiquid: true,
  ambientGlow: 'rgba(42, 193, 188, 0.24)',
  glassOverlay: 'rgba(255, 255, 255, 0.46)',
  glassStroke: 'rgba(255, 255, 255, 0.78)',
  glassHighlight: 'rgba(255, 255, 255, 0.9)',
  glassSurface: 'rgba(255, 255, 255, 0.54)',
  glassSurfaceSoft: 'rgba(255, 255, 255, 0.24)',
  glassSurfaceStrong: 'rgba(252, 255, 255, 0.88)',
  glassBorder: 'rgba(255, 255, 255, 0.72)',
  glassBorderStrong: 'rgba(255, 255, 255, 0.9)',
  glassSheen: 'rgba(255, 255, 255, 0.34)',
  glassTint: 'rgba(234, 255, 253, 0.18)',
  fieldSurface: 'rgba(252, 255, 255, 0.72)',
  fieldBorder: 'rgba(0, 91, 87, 0.12)',
  tabBarSurface: 'rgba(255, 255, 255, 0.82)',
  tabActiveSurface: 'rgba(0, 154, 148, 0.12)',
  scrim: 'rgba(19, 33, 31, 0.32)',
  cardShadow: shadow('0 4px 16px rgba(0, 74, 72, 0.04)', {
    shadowColor: '#004A48',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 0,
  }),
  floatingShadow: shadow('0 14px 30px rgba(0, 106, 103, 0.12)', {
    shadowColor: '#006A67',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 6,
  }),
};

const liquidDarkEffects: ThemeEffectTokens = {
  isLiquid: true,
  ambientGlow: 'rgba(108, 255, 244, 0.16)',
  glassOverlay: 'rgba(12, 35, 34, 0.78)',
  glassStroke: 'rgba(184, 255, 249, 0.22)',
  glassHighlight: 'rgba(233, 255, 252, 0.24)',
  glassSurface: 'rgba(18, 43, 41, 0.74)',
  glassSurfaceSoft: 'rgba(18, 48, 45, 0.48)',
  glassSurfaceStrong: 'rgba(13, 34, 33, 0.94)',
  glassBorder: 'rgba(184, 255, 249, 0.18)',
  glassBorderStrong: 'rgba(184, 255, 249, 0.34)',
  glassSheen: 'rgba(184, 255, 249, 0.12)',
  glassTint: 'rgba(108, 255, 244, 0.1)',
  fieldSurface: 'rgba(235, 255, 252, 0.1)',
  fieldBorder: 'rgba(184, 255, 249, 0.18)',
  tabBarSurface: 'rgba(5, 24, 23, 0.94)',
  tabActiveSurface: 'rgba(108, 255, 244, 0.14)',
  scrim: 'rgba(1, 10, 10, 0.78)',
  cardShadow: shadow('0 18px 46px rgba(0, 0, 0, 0.36)', {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.36,
    shadowRadius: 30,
    elevation: 7,
  }),
  floatingShadow: shadow('0 24px 60px rgba(0, 0, 0, 0.48)', {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.48,
    shadowRadius: 36,
    elevation: 11,
  }),
};

const makeComponents = (
  palette: ThemeColors,
  effects: ThemeEffectTokens,
): ThemeComponentTokens => ({
  screen: {
    flex: 1,
    backgroundColor: palette.background,
  },
  card: {
    backgroundColor: effects.isLiquid ? effects.glassSurface : palette.surface,
    borderWidth: 1,
    borderColor: effects.isLiquid ? effects.glassBorder : palette.divider,
    borderRadius: borderRadius.xl,
    ...continuous,
    ...effects.cardShadow,
  },
  elevatedCard: {
    backgroundColor: effects.isLiquid ? effects.glassSurfaceStrong : palette.surfaceElevated,
    borderWidth: 1,
    borderColor: effects.isLiquid ? effects.glassBorderStrong : palette.divider,
    borderRadius: borderRadius.xl,
    ...continuous,
    ...effects.floatingShadow,
  },
  surface: {
    backgroundColor: effects.isLiquid ? effects.glassSurfaceSoft : palette.surfaceAlt,
    borderWidth: 1,
    borderColor: effects.isLiquid ? effects.glassBorder : palette.divider,
    borderRadius: borderRadius.lg,
    ...continuous,
  },
  field: {
    backgroundColor: effects.isLiquid ? effects.fieldSurface : palette.surfaceAlt,
    borderWidth: 1.2,
    borderColor: effects.isLiquid ? effects.fieldBorder : palette.divider,
    borderRadius: borderRadius.lg,
    ...continuous,
  },
  subtleField: {
    backgroundColor: palette.primaryFaded,
    borderWidth: 1,
    borderColor: effects.isLiquid ? 'rgba(42, 193, 188, 0.16)' : palette.divider,
    borderRadius: borderRadius.lg,
    ...continuous,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.full,
    backgroundColor: effects.isLiquid ? effects.glassOverlay : palette.surfaceAlt,
    borderWidth: effects.isLiquid ? 1 : 0,
    borderColor: effects.glassStroke,
    alignItems: 'center',
    justifyContent: 'center',
    ...continuous,
  },
  tabBar: {
    backgroundColor: effects.isLiquid ? effects.tabBarSurface : palette.surface,
    borderTopWidth: 1,
    borderTopColor: effects.isLiquid ? effects.glassBorderStrong : palette.divider,
    ...effects.floatingShadow,
  },
  activeTab: {
    backgroundColor: effects.isLiquid ? effects.tabActiveSurface : palette.primaryFaded,
    borderWidth: 1,
    borderColor: effects.isLiquid ? effects.glassBorderStrong : palette.primaryFaded,
    ...continuous,
  },
  actionBar: {
    backgroundColor: effects.isLiquid ? palette.surfaceElevated : palette.surface,
    borderTopWidth: 1,
    borderTopColor: effects.isLiquid ? effects.glassStroke : palette.divider,
    ...effects.floatingShadow,
  },
  primaryButton: {
    backgroundColor: palette.primary,
    borderWidth: 1,
    borderColor: effects.isLiquid ? effects.glassBorderStrong : palette.primary,
    borderRadius: borderRadius.lg,
    ...continuous,
    ...effects.floatingShadow,
  },
  secondaryButton: {
    backgroundColor: palette.primaryFaded,
    borderWidth: 1,
    borderColor: effects.isLiquid ? effects.glassBorder : palette.primaryFaded,
    borderRadius: borderRadius.lg,
    ...continuous,
  },
  dangerButton: {
    backgroundColor: effects.isLiquid ? effects.glassSurfaceStrong : palette.surface,
    borderWidth: 1.5,
    borderColor: palette.error,
    borderRadius: borderRadius.lg,
    ...continuous,
  },
});

const createTheme = (
  variant: ThemeVariant,
  name: string,
  isDark: boolean,
  palette: ThemeColors,
  effects: ThemeEffectTokens,
  blurType: AppTheme['blurType'],
  blurAmount: number,
): AppTheme => {
  const components = makeComponents(palette, effects);

  return {
    variant,
    name,
    isDark,
    colors: palette,
    glassOverlay: effects.glassOverlay,
    blurType,
    blurAmount,
    cardStyle: components.card,
    surfaceStyle: components.surface,
    effects,
    components,
  };
};

export const themes: Record<ThemeVariant, AppTheme> = {
  classic: createTheme('classic', 'Classic', false, classicColors, classicEffects, 'light', 10),
  liquid_light: createTheme(
    'liquid_light',
    'Liquid Glass Light',
    false,
    liquidLightColors,
    liquidLightEffects,
    'thickMaterial',
    28,
  ),
  liquid_dark: createTheme(
    'liquid_dark',
    'Liquid Glass Dark',
    true,
    liquidDarkColors,
    liquidDarkEffects,
    'thickMaterial',
    28,
  ),
};
